---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # See: https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing
  application.instanceLabelKey: "argocd.argoproj.io/instance"
