bases:
- ../bases/upstream-argocd
images:
- name: quay.io/argoproj/argocd
  newName: quay.io/giantswarm/argocd
  newTag: v2.1.0
namespace: argocd
patchesStrategicMerge:
- argocd-cm.yaml
- argocd-dex-server-rbac.yaml
- argocd-repo-server-deploy.yaml
- argocd-server-rbac.yaml
- service-metrics-patch.yaml
resources:
- argocd-namespace.yaml
- argocd-dex-server-psp.yaml
- argocd-redis-psp.yaml
- argocd-redis-rbac.yaml
- argocd-repo-server-sa.yaml
- argocd-repo-server-psp.yaml
- argocd-repo-server-rbac.yaml
- argocd-server-psp.yaml
- argocd-ingress.yaml
- argocd-applications.yaml
